---
apiVersion: v1
kind: Namespace
metadata:
  name: model-serving-prod
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: model-serving-dev
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---